---
title: Siteleaf Learn
url: http://learn.siteleaf.com
timezone: Eastern Time (US & Canada)
collections:
  api:
    title: API
    output: true
    weight: 4
  getting-started:
    title: Getting Started
    meta:
      description: Learn more about Siteleaf itself
    output: true
    weight: 0
  managing-content:
    title: Managing Content
    meta:
      description: How to manage content
    output: true
    weight: 1
  posts:
    title: Posts
    output: true
  theme-development:
    title: Theme Development
    meta:
      description: How to make your own themes
    output: true
    weight: 2
  uploads:
    title: Uploads
    output: true
  users-and-settings:
    title: Users and Settings
    meta:
      description: Add your friends and host
    output: true
    weight: 3
defaults:
- scope:
    path: ''
    type: posts
  values:
    foo: bar
- scope:
    path: ''
    type: api
  values:
    layout: api
