---
title: Siteleaf Documentation
timezone: America/New_York
collections:
  api:
    title: API
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Integrate directly into your site or app
      icon: cloud
      in_nav: true
    position: 60
  sites:
    title: Deploy and Collaborate
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Publish your site and invite other users
      icon: globe
      in_nav: true
    position: 50
  getting-started:
    title: Getting Started
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Learn more about Siteleaf itself
      icon: home
      in_nav: true
    position: 10
  content:
    title: Managing Content
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Pages, collections, posts, metadata
      icon: write
      in_nav: true
    position: 30
  posts:
    title: Posts
    output: true
  v2:
    title: Siteleaf v2
    output: true
    permalink: "/:collection/:path/"
    position: 20
    meta:
      description: What's new in v2
      icon: info
      in_nav: true
  themes:
    title: Theme Development
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Liquid, Sass, Jekyll, syncing, local dev
      icon: bezier
      in_nav: true
    position: 40
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: api
  values:
    layout: api
permalink: pretty
github_url: https://github.com/siteleaf/learn.siteleaf.com
sass:
  style: compressed
gems:
- jekyll-sitemap
