---
title: Siteleaf Learn
url: http://learn.siteleaf.com
timezone: America/New_York
github_url: https://github.com/siteleaf/learn.siteleaf.com
collections:
  api:
    title: API
    output: true
    meta:
      description: Interact directly with our API
      icon: globe
      in_nav: true
    weight: 60
  getting-started:
    title: Getting Started
    output: true
    meta:
      description: Learn more about Siteleaf itself
      icon: home
      in_nav: true
    weight: 10
  managing-content:
    title: Managing Content
    output: true
    meta:
      description: How to manage content
      icon: write
      in_nav: true
    weight: 30
  posts:
    title: Posts
    output: true
  siteleaf-v2:
    title: Siteleaf V2
    output: true
    weight: 20
    meta:
      description: What's new in V2
      icon: info
      in_nav: true
  theme-development:
    title: Theme Development
    output: true
    meta:
      description: How to make your own themes
      icon: bezier
      in_nav: true
    weight: 40
  uploads:
    title: Uploads
    output: true
  users-and-settings:
    title: Users and Settings
    output: true
    meta:
      description: Add your friends and host
      icon: users
      in_nav: true
    weight: 50
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: api
  values:
    layout: api
