---
title: Siteleaf Learn
timezone: America/New_York
collections:
  getting-started:
    title: Getting Started
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Learn more about Siteleaf itself
      icon: home
      badge: "/uploads/badge--getting-started.png"
      in_nav: true
    position: 10
  content:
    title: Managing Content
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Pages, collections, posts, metadata
      icon: write
      badge: "/uploads/badge--getting-started.png"
      in_nav: true
    position: 30
  themes:
    title: Developing Themes
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Liquid, Sass, Jekyll, syncing, local dev
      icon: bezier
      badge: "/uploads/badge--getting-started.png"
      in_nav: true
    position: 40
  sites:
    title: Deploy & Collaborate
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Publish your site and invite other users
      icon: globe
      badge: "/uploads/badge--getting-started.png"
      in_nav: true
    position: 50
  api:
    title: API
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Integrate directly into your site or app
      icon: cloud
      badge: "/uploads/badge--getting-started.png"
      in_nav: true
    position: 60
  v1:
    title: Legacy Sites
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Moving from v1 to v2
      icon: info
      badge: "/uploads/badge--getting-started.png"
      in_nav: true
    position: 70
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: getting-started
  values:
    layout: page
    color: blue
- scope:
    path: ''
    type: content
  values:
    layout: page
    color: green
- scope:
    path: ''
    type: themes
  values:
    layout: page
    color: yellow
- scope:
    path: ''
    type: sites
  values:
    layout: page
    color: red
- scope:
    path: ''
    type: api
  values:
    layout: page
    color: purple
- scope:
    path: ''
    type: v1
  values:
    layout: page
url: http://learn.siteleaf.com
permalink: pretty
github_url: https://github.com/siteleaf/learn.siteleaf.com
sass:
  style: compressed
gems:
- jekyll-sitemap
- jekyll-seo-tag
logo: "/assets/images/logo.svg"
