---
title: Siteleaf Learn
url: http://learn.siteleaf.com
timezone: Eastern Time (US & Canada)
collections:
  getting-started:
    title: Getting Started
    output: true
    weight: 0
  managing-content:
    title: Managing Content
    output: true
    weight: 1
  theme-development:
    title: Theme Development
    output: true
    weight: 2
  uploads:
    title: Uploads
    output: true
  users-and-settings:
    title: Users and Settings
    output: true
    weight: 3
defaults:
- scope:
    path: ''
    type: posts
  values:
    foo: bar
